timeout: 900s
steps:
  - name: node
    entrypoint: npm
    args:
      - run
      - build
  - name: node
    entrypoint: npm
    env:
      - NPM_TOKEN=$_NPM_TOKEN
    args:
      - publish
      - --prefix
      - dist/ng-grid-system
